# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-16 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170614_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextremealert',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
