# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_userextremealert_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('val', models.PositiveIntegerField(blank=True, default=0)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
            ],
            options={
                'db_table': 'stock_stat',
            },
        ),
    ]
