# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-28 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_stockstat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockstat',
            unique_together=set([('symbol', 'date')]),
        ),
    ]
