"""
Django settings for momo project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'zd$fb3u%bw$+yhewjcw)ev%ea&$e8@f8dy%kq4b+tr1w=ns6k3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'djstripe',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.twitter',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'push_notifications',
    'rest_framework',
    'dashboard'
]

SITE_ID = 1

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'momo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'momo.wsgi.application'
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',
    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('RDS_DB_NAME'),
        'USER': os.environ.get('RDS_USERNAME'),
        'PASSWORD': os.environ.get('RDS_PASSWORD'),
        'HOST': os.environ.get('RDS_HOSTNAME'),
        'PORT': os.environ.get('RDS_PORT', '3306'),
    }
}

STRIPE_PUBLIC_KEY = os.environ.get("STRIPE_PUBLIC_KEY", "pk_live_VoSefaaDhM4UBDQIky6i59OU")
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "sk_live_86H9j3O60Yl8tSw7pZczRdXW")


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
PROJECT_URL = 'https://momoweb.mometic.com'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]

# STATICFILES_STORAGE='django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

LOGIN_REDIRECT_URL = '/dashboard'

DJSTRIPE_PLANS = {
    "daily": {
        "stripe_plan_id": "pro-daily",
        "name": "Daily",
        "description": "Unlimited use",
        "price": 100,
        "currency": "usd",
        "interval": "day",
        "discount": ''
    },
    "monthly": {
        "stripe_plan_id": "pro-monthly",
        "name": "Monthly",
        "description": "Unlimited use",
        "price": 1099,
        "currency": "usd",
        "interval": "month",
        "discount": ''
    },
    "quaterly": {
        "stripe_plan_id": "pro-quarterly",
        "name": "Quarterly",
        "description": "Unlimited use",
        "price": 2299,
        "currency": "usd",
        "interval": "month",
        "interval_count": 3,
        "discount": '25%'
    },
    "yearly": {
        "stripe_plan_id": "pro-yearly",
        "name": "Yearly",
        "description": "Unlimited use",
        "price": 7200,
        "currency": "usd",
        "interval": "year",
        "discount": '40%'
    }
}

EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'

#SOCIALACCOUNT_EMAIL_REQUIRED=True
SOCIALACCOUNT_QUERY_EMAIL=True
ACCOUNT_EMAIL_REQUIRED=True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

PUSH_NOTIFICATIONS_SETTINGS = {
    'FCM_API_KEY': 'AAAAARK3X2U:APA91bFtvkqzzVIz4Pv7yNG6zLEXpUFRYnq7dr6XicvYIf82v2Tx70E0jOjhfvKdqWnA--xTAGxbFvulZpZjRsQlRIwDBfAVjlahStdEvIqNh8Hk13UnoZF0F0dT3E9_f0NqyyEpfSYU',
    'UPDATE_ON_DUPLICATE_REG_ID': True,
    'FCM_ERROR_TIMEOUT': 15
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format':
                '%(levelname)s|%(asctime)s|%(name)s>> %(message)s',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': '/tmp/django.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file','console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

REDIS = {
    'host': 'localhost',
    'port': 6379,
    'db': 0
}

QUOTE_DATA_API_URL = 'http://activetickquote.us-east-1.elasticbeanstalk.com/quoteData?field=5+10+11+27&symbol=%s'